apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexcellent-worker
  labels:
    app: flexcellent-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flexcellent-worker
  template:
    metadata:
      labels:
        app: flexcellent-worker
    spec:
      containers:
        - name: flexcellent-worker
          image: sassy2711/flexcellent-backend:latest
          imagePullPolicy: Always
          env:
            - name: RUNNING_IN_DOCKER
              value: "1"
            - name: SDL_AUDIODRIVER
              value: "dummy"
          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      restartPolicy: Always
